### ISSUE TITLE
Cannot start cluster

### ISSUE THREAD

**Issue by lewiswon** [MicroRaft/AfloatDB#3]
When all node startup, node cannot communication with each other. macOS Ventura , JDK 11
Node 1 log
`16:48:44.583 [RaftRpc-17] ERROR io.microraft.afloatdb.internal.rpc.RaftRpcService - node1 Raft RPC stream to node3 has failed. Exception: StatusRuntimeException Message: DEADLINE_EXCEEDED: deadline exceeded after 9.995382590s. [buffered_nanos=48380599, remote_addr=/127.0.0.1:6769]
16:48:53.062 [RaftRpc-25] ERROR io.microraft.afloatdb.internal.rpc.RaftRpcService - node1 Raft RPC stream to node2 has failed. Exception: StatusRuntimeException Message: DEADLINE_EXCEEDED: deadline exceeded after 9.997887682s. [buffered_nanos=35821362, remote_addr=/127.0.0.1:6768]
`
Node 2 log
`16:49:11.524 [Raft-0] INFO - [RaftNode] node2<afloatdb-test-cluster> Pre-vote started for next term: 1, last log index: 0, last log term: 0
16:49:11.526 [Raft-0] INFO - [RaftRpcService] AfloatDBEndpoint{id=node2} initialized stub for AfloatDBEndpoint{id=node3}
16:49:11.528 [RaftRpc-33] ERROR - [RaftRpcService] node2 Raft RPC stream to node3 has failed. Exception: StatusRuntimeException Message: UNKNOWN`

Node 3 log
`[RaftRpcService] node3 Raft RPC stream to node2 has failed. Exception: StatusRuntimeException Message: UNKNOWN`

**Comment by metanet** [comment]
Hi @lewiswon 

can you share your config and full logs

**Comment by lewiswon** [comment]
I use default config file, just change address from localhost to 127.0.0.1, localhost won't work either, it's resolved to a ip start with 169.*
[node1.log](https://github.com/MicroRaft/AfloatDB/files/11132100/node1.log)
[node2.log](https://github.com/MicroRaft/AfloatDB/files/11132101/node2.log)
[node3.log](https://github.com/MicroRaft/AfloatDB/files/11132102/node3.log)
[node1.conf.txt](https://github.com/MicroRaft/AfloatDB/files/11132105/node1.conf.txt)
[node2.conf.txt](https://github.com/MicroRaft/AfloatDB/files/11132106/node2.conf.txt)
[node3.conf.txt](https://github.com/MicroRaft/AfloatDB/files/11132107/node3.conf.txt)

**Comment by metanet** [comment]
thanks. logs show that nodes cannot talk to each other. 

https://github.com/MicroRaft/AfloatDB/blob/master/afloatdb-server/src/main/java/io/microraft/afloatdb/internal/rpc/impl/RpcServerImpl.java#L73-L76 this is how the netty server is started. i think something is wrong either in your network setup or how code handles your network condition.

**Comment by lewiswon** [comment]
Thanks for reply, I rebuild the project, now cluster can start up and select leader, but the timeout error still exists, I'am not familiar with grpc, I'll close issue, and look at grpc first.
